// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: irc.proto

package ircservice;

public final class Irc {
  private Irc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_ircservice_IRCMessage_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ircservice_IRCMessage_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_ircservice_JoinRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ircservice_JoinRequest_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_ircservice_JoinReply_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ircservice_JoinReply_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_ircservice_RetrieveRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ircservice_RetrieveRequest_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_ircservice_RetrieveReply_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ircservice_RetrieveReply_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_ircservice_PostMessageRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ircservice_PostMessageRequest_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_ircservice_PostMessageReply_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ircservice_PostMessageReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tirc.proto\022\nircservice\">\n\nIRCMessage\022\014\n" +
      "\004nick\030\001 \001(\t\022\017\n\007content\030\002 \001(\t\022\021\n\ttimestam" +
      "p\030\003 \001(\003\"\"\n\013JoinRequest\022\023\n\013channelName\030\001 " +
      "\001(\t\"\032\n\tJoinReply\022\r\n\005isNew\030\001 \001(\010\"9\n\017Retri" +
      "eveRequest\022\023\n\013channelName\030\001 \001(\t\022\021\n\ttimes" +
      "tamp\030\002 \001(\003\"5\n\rRetrieveReply\022$\n\004msgs\030\001 \003(" +
      "\0132\026.ircservice.IRCMessage\"^\n\022PostMessage" +
      "Request\022\023\n\013channelName\030\001 \001(\t\022\014\n\004nick\030\002 \001" +
      "(\t\022\022\n\ntheMessage\030\003 \001(\t\022\021\n\ttimestamp\030\004 \001(" +
      "\003\"%\n\020PostMessageReply\022\021\n\tisSuccess\030\001 \001(\010",
      "2\337\001\n\nIRCService\022=\n\013joinChannel\022\027.ircserv" +
      "ice.JoinRequest\032\025.ircservice.JoinReply\022E" +
      "\n\013getMessages\022\033.ircservice.RetrieveReque" +
      "st\032\031.ircservice.RetrieveReply\022K\n\013sendMes" +
      "sage\022\036.ircservice.PostMessageRequest\032\034.i" +
      "rcservice.PostMessageReplyB\016\n\nircservice" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ircservice_IRCMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ircservice_IRCMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ircservice_IRCMessage_descriptor,
        new java.lang.String[] { "Nick", "Content", "Timestamp", });
    internal_static_ircservice_JoinRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ircservice_JoinRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ircservice_JoinRequest_descriptor,
        new java.lang.String[] { "ChannelName", });
    internal_static_ircservice_JoinReply_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ircservice_JoinReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ircservice_JoinReply_descriptor,
        new java.lang.String[] { "IsNew", });
    internal_static_ircservice_RetrieveRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ircservice_RetrieveRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ircservice_RetrieveRequest_descriptor,
        new java.lang.String[] { "ChannelName", "Timestamp", });
    internal_static_ircservice_RetrieveReply_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ircservice_RetrieveReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ircservice_RetrieveReply_descriptor,
        new java.lang.String[] { "Msgs", });
    internal_static_ircservice_PostMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ircservice_PostMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ircservice_PostMessageRequest_descriptor,
        new java.lang.String[] { "ChannelName", "Nick", "TheMessage", "Timestamp", });
    internal_static_ircservice_PostMessageReply_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_ircservice_PostMessageReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ircservice_PostMessageReply_descriptor,
        new java.lang.String[] { "IsSuccess", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
