// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: irc.proto

package ircservice;

public interface IRCMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ircservice.IRCMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string nick = 1;</code>
   */
  java.lang.String getNick();
  /**
   * <code>optional string nick = 1;</code>
   */
  com.google.protobuf.ByteString
      getNickBytes();

  /**
   * <code>optional string content = 2;</code>
   */
  java.lang.String getContent();
  /**
   * <code>optional string content = 2;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>optional int64 timestamp = 3;</code>
   */
  long getTimestamp();
}
