// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: irc.proto

package ircservice;

public interface JoinReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ircservice.JoinReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool isNew = 1;</code>
   */
  boolean getIsNew();
}
