// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: irc.proto

package ircservice;

public interface JoinRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ircservice.JoinRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string channelName = 1;</code>
   */
  java.lang.String getChannelName();
  /**
   * <code>optional string channelName = 1;</code>
   */
  com.google.protobuf.ByteString
      getChannelNameBytes();
}
