// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: irc.proto

package ircservice;

public interface PostMessageReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ircservice.PostMessageReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool isSuccess = 1;</code>
   */
  boolean getIsSuccess();
}
