// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: irc.proto

package ircservice;

public interface PostMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ircservice.PostMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string channelName = 1;</code>
   */
  java.lang.String getChannelName();
  /**
   * <code>optional string channelName = 1;</code>
   */
  com.google.protobuf.ByteString
      getChannelNameBytes();

  /**
   * <code>optional string nick = 2;</code>
   */
  java.lang.String getNick();
  /**
   * <code>optional string nick = 2;</code>
   */
  com.google.protobuf.ByteString
      getNickBytes();

  /**
   * <code>optional string theMessage = 3;</code>
   */
  java.lang.String getTheMessage();
  /**
   * <code>optional string theMessage = 3;</code>
   */
  com.google.protobuf.ByteString
      getTheMessageBytes();

  /**
   * <code>optional int64 timestamp = 4;</code>
   */
  long getTimestamp();
}
