// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: irc.proto

package ircservice;

/**
 * Protobuf type {@code ircservice.RetrieveReply}
 */
public  final class RetrieveReply extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ircservice.RetrieveReply)
    RetrieveReplyOrBuilder {
  // Use RetrieveReply.newBuilder() to construct.
  private RetrieveReply(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RetrieveReply() {
    msgs_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private RetrieveReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              msgs_ = new java.util.ArrayList<ircservice.IRCMessage>();
              mutable_bitField0_ |= 0x00000001;
            }
            msgs_.add(input.readMessage(ircservice.IRCMessage.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        msgs_ = java.util.Collections.unmodifiableList(msgs_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ircservice.Irc.internal_static_ircservice_RetrieveReply_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ircservice.Irc.internal_static_ircservice_RetrieveReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ircservice.RetrieveReply.class, ircservice.RetrieveReply.Builder.class);
  }

  public static final int MSGS_FIELD_NUMBER = 1;
  private java.util.List<ircservice.IRCMessage> msgs_;
  /**
   * <code>repeated .ircservice.IRCMessage msgs = 1;</code>
   */
  public java.util.List<ircservice.IRCMessage> getMsgsList() {
    return msgs_;
  }
  /**
   * <code>repeated .ircservice.IRCMessage msgs = 1;</code>
   */
  public java.util.List<? extends ircservice.IRCMessageOrBuilder> 
      getMsgsOrBuilderList() {
    return msgs_;
  }
  /**
   * <code>repeated .ircservice.IRCMessage msgs = 1;</code>
   */
  public int getMsgsCount() {
    return msgs_.size();
  }
  /**
   * <code>repeated .ircservice.IRCMessage msgs = 1;</code>
   */
  public ircservice.IRCMessage getMsgs(int index) {
    return msgs_.get(index);
  }
  /**
   * <code>repeated .ircservice.IRCMessage msgs = 1;</code>
   */
  public ircservice.IRCMessageOrBuilder getMsgsOrBuilder(
      int index) {
    return msgs_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < msgs_.size(); i++) {
      output.writeMessage(1, msgs_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < msgs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, msgs_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static ircservice.RetrieveReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ircservice.RetrieveReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ircservice.RetrieveReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ircservice.RetrieveReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ircservice.RetrieveReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static ircservice.RetrieveReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static ircservice.RetrieveReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static ircservice.RetrieveReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static ircservice.RetrieveReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static ircservice.RetrieveReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ircservice.RetrieveReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ircservice.RetrieveReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ircservice.RetrieveReply)
      ircservice.RetrieveReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ircservice.Irc.internal_static_ircservice_RetrieveReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ircservice.Irc.internal_static_ircservice_RetrieveReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ircservice.RetrieveReply.class, ircservice.RetrieveReply.Builder.class);
    }

    // Construct using ircservice.RetrieveReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getMsgsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (msgsBuilder_ == null) {
        msgs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        msgsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ircservice.Irc.internal_static_ircservice_RetrieveReply_descriptor;
    }

    public ircservice.RetrieveReply getDefaultInstanceForType() {
      return ircservice.RetrieveReply.getDefaultInstance();
    }

    public ircservice.RetrieveReply build() {
      ircservice.RetrieveReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public ircservice.RetrieveReply buildPartial() {
      ircservice.RetrieveReply result = new ircservice.RetrieveReply(this);
      int from_bitField0_ = bitField0_;
      if (msgsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          msgs_ = java.util.Collections.unmodifiableList(msgs_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.msgs_ = msgs_;
      } else {
        result.msgs_ = msgsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ircservice.RetrieveReply) {
        return mergeFrom((ircservice.RetrieveReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ircservice.RetrieveReply other) {
      if (other == ircservice.RetrieveReply.getDefaultInstance()) return this;
      if (msgsBuilder_ == null) {
        if (!other.msgs_.isEmpty()) {
          if (msgs_.isEmpty()) {
            msgs_ = other.msgs_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMsgsIsMutable();
            msgs_.addAll(other.msgs_);
          }
          onChanged();
        }
      } else {
        if (!other.msgs_.isEmpty()) {
          if (msgsBuilder_.isEmpty()) {
            msgsBuilder_.dispose();
            msgsBuilder_ = null;
            msgs_ = other.msgs_;
            bitField0_ = (bitField0_ & ~0x00000001);
            msgsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getMsgsFieldBuilder() : null;
          } else {
            msgsBuilder_.addAllMessages(other.msgs_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ircservice.RetrieveReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ircservice.RetrieveReply) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<ircservice.IRCMessage> msgs_ =
      java.util.Collections.emptyList();
    private void ensureMsgsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        msgs_ = new java.util.ArrayList<ircservice.IRCMessage>(msgs_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        ircservice.IRCMessage, ircservice.IRCMessage.Builder, ircservice.IRCMessageOrBuilder> msgsBuilder_;

    /**
     * <code>repeated .ircservice.IRCMessage msgs = 1;</code>
     */
    public java.util.List<ircservice.IRCMessage> getMsgsList() {
      if (msgsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(msgs_);
      } else {
        return msgsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ircservice.IRCMessage msgs = 1;</code>
     */
    public int getMsgsCount() {
      if (msgsBuilder_ == null) {
        return msgs_.size();
      } else {
        return msgsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ircservice.IRCMessage msgs = 1;</code>
     */
    public ircservice.IRCMessage getMsgs(int index) {
      if (msgsBuilder_ == null) {
        return msgs_.get(index);
      } else {
        return msgsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ircservice.IRCMessage msgs = 1;</code>
     */
    public Builder setMsgs(
        int index, ircservice.IRCMessage value) {
      if (msgsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMsgsIsMutable();
        msgs_.set(index, value);
        onChanged();
      } else {
        msgsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ircservice.IRCMessage msgs = 1;</code>
     */
    public Builder setMsgs(
        int index, ircservice.IRCMessage.Builder builderForValue) {
      if (msgsBuilder_ == null) {
        ensureMsgsIsMutable();
        msgs_.set(index, builderForValue.build());
        onChanged();
      } else {
        msgsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ircservice.IRCMessage msgs = 1;</code>
     */
    public Builder addMsgs(ircservice.IRCMessage value) {
      if (msgsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMsgsIsMutable();
        msgs_.add(value);
        onChanged();
      } else {
        msgsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ircservice.IRCMessage msgs = 1;</code>
     */
    public Builder addMsgs(
        int index, ircservice.IRCMessage value) {
      if (msgsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMsgsIsMutable();
        msgs_.add(index, value);
        onChanged();
      } else {
        msgsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ircservice.IRCMessage msgs = 1;</code>
     */
    public Builder addMsgs(
        ircservice.IRCMessage.Builder builderForValue) {
      if (msgsBuilder_ == null) {
        ensureMsgsIsMutable();
        msgs_.add(builderForValue.build());
        onChanged();
      } else {
        msgsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ircservice.IRCMessage msgs = 1;</code>
     */
    public Builder addMsgs(
        int index, ircservice.IRCMessage.Builder builderForValue) {
      if (msgsBuilder_ == null) {
        ensureMsgsIsMutable();
        msgs_.add(index, builderForValue.build());
        onChanged();
      } else {
        msgsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ircservice.IRCMessage msgs = 1;</code>
     */
    public Builder addAllMsgs(
        java.lang.Iterable<? extends ircservice.IRCMessage> values) {
      if (msgsBuilder_ == null) {
        ensureMsgsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, msgs_);
        onChanged();
      } else {
        msgsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ircservice.IRCMessage msgs = 1;</code>
     */
    public Builder clearMsgs() {
      if (msgsBuilder_ == null) {
        msgs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        msgsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ircservice.IRCMessage msgs = 1;</code>
     */
    public Builder removeMsgs(int index) {
      if (msgsBuilder_ == null) {
        ensureMsgsIsMutable();
        msgs_.remove(index);
        onChanged();
      } else {
        msgsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ircservice.IRCMessage msgs = 1;</code>
     */
    public ircservice.IRCMessage.Builder getMsgsBuilder(
        int index) {
      return getMsgsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ircservice.IRCMessage msgs = 1;</code>
     */
    public ircservice.IRCMessageOrBuilder getMsgsOrBuilder(
        int index) {
      if (msgsBuilder_ == null) {
        return msgs_.get(index);  } else {
        return msgsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ircservice.IRCMessage msgs = 1;</code>
     */
    public java.util.List<? extends ircservice.IRCMessageOrBuilder> 
         getMsgsOrBuilderList() {
      if (msgsBuilder_ != null) {
        return msgsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(msgs_);
      }
    }
    /**
     * <code>repeated .ircservice.IRCMessage msgs = 1;</code>
     */
    public ircservice.IRCMessage.Builder addMsgsBuilder() {
      return getMsgsFieldBuilder().addBuilder(
          ircservice.IRCMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .ircservice.IRCMessage msgs = 1;</code>
     */
    public ircservice.IRCMessage.Builder addMsgsBuilder(
        int index) {
      return getMsgsFieldBuilder().addBuilder(
          index, ircservice.IRCMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .ircservice.IRCMessage msgs = 1;</code>
     */
    public java.util.List<ircservice.IRCMessage.Builder> 
         getMsgsBuilderList() {
      return getMsgsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        ircservice.IRCMessage, ircservice.IRCMessage.Builder, ircservice.IRCMessageOrBuilder> 
        getMsgsFieldBuilder() {
      if (msgsBuilder_ == null) {
        msgsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            ircservice.IRCMessage, ircservice.IRCMessage.Builder, ircservice.IRCMessageOrBuilder>(
                msgs_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        msgs_ = null;
      }
      return msgsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:ircservice.RetrieveReply)
  }

  // @@protoc_insertion_point(class_scope:ircservice.RetrieveReply)
  private static final ircservice.RetrieveReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ircservice.RetrieveReply();
  }

  public static ircservice.RetrieveReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RetrieveReply>
      PARSER = new com.google.protobuf.AbstractParser<RetrieveReply>() {
    public RetrieveReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new RetrieveReply(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<RetrieveReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RetrieveReply> getParserForType() {
    return PARSER;
  }

  public ircservice.RetrieveReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

